language: cpp
compiler:
  - gcc

sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -y update
  - sudo apt-get -y install g++-5
  - sudo apt-get -y install libboost-all-dev
  - sudo apt-get -y install libpcap-dev

script:
  - ./build.sh 4
